CREATE TABLE IF NOT EXISTS "project" (
  "id" SERIAL8 PRIMARY KEY NOT NULL,
  "title" VARCHAR(255) UNIQUE NOT NULL,
  "text" TEXT DEFAULT '' NOT NULL,
  "url" TEXT UNIQUE,
  "datetime" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
